--liquibase formatted sql

--changeset rgurinovich:1
create table if not exists users(
    id bigint primary key generated by default as identity,
    username varchar(100) unique not null ,
    email varchar(100) unique not null ,
    password varchar(100) not null
);

--changeset rgurinovich:2
create table if not exists bouquets(
    id   bigint generated by default as identity primary key,
    title       varchar(255) not null,
    description varchar(255),
    price       decimal,
    created_at  timestamp(6) with time zone,
    created_by  bigint references users(id) not null ,
    modified_at timestamp(6) with time zone,
    modified_by bigint references users(id) not null
);